### ISSUE TITLE
ReferenceError: print is not defined trying to run after bundling

### ISSUE THREAD

**Issue by ShivamJoker** [vercel/satori#224] opened 2022-10-17 10:20 UTC
# Bug report
I am trying the basic example to run in NodeJS after bundling the `JSX` into `mjs` using `esbuild` but it is giving me error

```
         Module["print"] = print;
                            ^

ReferenceError: print is not defined
    at file:///home/shivam/learnaws/youtube-notifier/satroi.mjs:443:29
    at node_modules/.pnpm/yoga-layout-prebuilt@1.10.0/node_modules/yoga-layout-prebuilt/yoga-layout/dist/entry-browser.js
```

## Expected Behavior
I want satori to give me SVG after bundling the library

## Reproduction

```tsx
import satori from "satori";
import { readFile, writeFile } from "node:fs/promises";
import React from "react";

const makeSvg = async () => {
  const font = await readFile("./lambda/inter-latin-ext-400-normal.woff");
  const svg = await satori(
    <div
      style={{
        height: "100%",
        width: "100%",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#fff",
        fontSize: 32,
        fontWeight: 600,
      }}
    >
      <svg
        width="75"
        viewBox="0 0 75 65"
        fill="#000"
        style={{ margin: "0 75px" }}
      >
        <path d="M37.59.25l36.95 64H.64l36.95-64z"></path>
      </svg>
      <div style={{ marginTop: 40 }}>Hello, World</div>
    </div>,
    {
      width: 1280,
      height: 780,
      fonts: [{ data: font, name: "Inter", weight: 400, style: "normal" }],
    }
  );
  await writeFile("./thumb.svg", svg);
};

makeSvg();
```

Compile it with `esbuild`

```sh
esbuild createThumb.tsx --outfile=createThumb.mjs --bundle --platform=node
```
Run it in Node

```
node createThumb.mjs
```

## Additional Context
esbuild - 0.15.8
satori -    ^0.0.42
node - v16.17.1

**Comment by wong2** [comment] 2022-10-17 11:25
I've found the cause: satori depends on `yoga-layout-prebuilt`, which includes a prebuilt version of yoga: https://github.com/vadimdemedes/yoga-layout-prebuilt/blob/master/yoga-layout/build/Release/nbind.js#L33 (warning: file is large).
The code checks if the running environment is node with this:
`ENVIRONMENT_IS_NODE = typeof process === "object" && typeof require === "function" && !ENVIRONMENT_IS_WEB && !ENVIRONMENT_IS_WORKER;`

You know that `require` is not defined in `.mjs` files, so the check fails, and the environment falls back to be SHELL, which causes the issue.

**Comment by wong2** [comment] 2022-10-17 11:28
@shuding The yoga-layout-prebuilt build is too old, which is outdated, I think it'll be better to maintain a new prebuilt package of yoga-layout.

**Comment by wong2** [comment] 2022-10-17 11:50
Yeah i think that will work

**Comment by ShivamJoker** [comment] 2022-10-21 12:32
@wong2 @shuding even after adding fallback for require I am getting this error

```sh
file:///home/shivam/learnaws/youtube-notifier/lambda/dist/createThumb.mjs:439
            throw ex;
            ^

ReferenceError: _a is not defined
    at file:///home/shivam/learnaws/youtube-notifier/lambda/dist/createThumb.mjs:2675:12
    at file:///home/shivam/learnaws/youtube-notifier/lambda/dist/createThumb.mjs:3659:9
    at node_modules/.pnpm/yoga-layout-prebuilt@1.10.0/node_modules/yoga-layout-prebuilt/yoga-layout/dist/entry-browser.js (file:///home/shivam/learnaws/youtube-notifier/lambda/dist/createThumb.mjs:27920:5)
    at __require2 (file:///home/shivam/learnaws/youtube-notifier/lambda/dist/createThumb.mjs:16:52)
    at file:///home/shivam/learnaws/youtube-notifier/lambda/dist/createThumb.mjs:39750:18
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
```

**Comment by shuding** [comment] 2022-10-21 12:37
That looks like the same one as #185, I think we can add something to our build script to work around it.

**Comment by ShivamJoker** [comment] 2022-10-21 15:59
> That looks like the same one as #185, I think we can add something to our build script to work around it.

It would be great to get this fixed at least, so I don't need to create a lambda layer to make it work.

**Comment by shuding** [comment] 2023-02-07 08:53
I believe this is now fixed as we replaced the prebuilt yoga completely. Let me know if it is not!

**Closed by shuding** 2023-02-07 08:53 UTC
