### ISSUE TITLE
Bengali Font breaks

### ISSUE THREAD

**Issue by hasinoorit** [vercel/satori#538] opened 2023-09-08 06:55 UTC
# Bengali text are breaking even if i use custom font

## Description / Observed Behavior

It can not render Bengali text properly
<img width="1200" alt="Screenshot 2023-09-08 at 12 45 16 PM" src="https://github.com/vercel/satori/assets/13180268/8a63ff86-0b2c-495e-a01c-1445cbc33d96">

## Expected Behavior

It should render Bengali text as well
<img width="695" alt="Screenshot 2023-09-08 at 12 54 48 PM" src="https://github.com/vercel/satori/assets/13180268/660927e3-4bdf-49d9-a0db-26eb0f0bd5f9">

## Reproduction

```tsx
import { ImageResponse } from 'next/server'
// App router includes @vercel/og.
// No need to install it.

export const runtime = 'edge'

export async function GET() {
  const fontData = await fetch(
    'https://cdn.jsdelivr.net/gh/sh4hids/bangla-web-fonts@solaimanlipi/subset-SolaimanLipiNormal.ttf'
  ).then((res) => res.arrayBuffer())
  return new ImageResponse(
    (
      <div
        style={{
          fontSize: 40,
          color: 'black',
          background: 'white',
          width: '100%',
          height: '100%',
          padding: '50px 200px',
          textAlign: 'center',
          justifyContent: 'center',
          alignItems: 'center',
          fontFamily: 'SolaimanLipi',
        }}
        lang="bn-IN"
      >
        বিজ্ঞান ও সাহিত্য
      </div>
    ),
    {
      width: 1200,
      height: 630,
      fonts: [{ name: 'SolaimanLipi', data: fontData, weight: 400 }],
    }
  )
}
```

Minimum reproduction [link](https://og-playground.vercel.app/?share=XZK9TuswFMdfxTroqktv60vT9GKVDnxIMDCBxJIlrZ3E4MRR4vSDqo_AxIqYUGBAYoUFXiWPwnFCEDBEOef3t8_f59hrmGkugMGYy7mXEJKblRK767WNCYmEDCPDSOcfpX863QYuJDfRL8Zlnip_hTRQYtlSGx_ITMyM1AlqM62KOGlVX8kwOTYizq0kEiOyVroociOD1b5GmFj_n_LUn12GmS4Svq-VzlDfCoLgyxV3ncorwchg-xs6_-zFpbSmm42XTGwwzufht852PRgNPWjIXIrFnl4io4SS0ZC4X1IglUK-RSltUTs8EvtZKG3Hdk-67NRmhNR2aJj6JiIcN58MRr3hTm97qAZubwerO0c912mSv65z5cFk3Lerm4P28aRNhLf12-1Mp4w4FK0mVflUle9VeVs9XFflXVW-VeUjqcob_F7q7LXW72v9edzHcli3_UMXdGqvLAe2hnoowP7j2KB5D8Acm3AxLUJgga9y0QUR6wt5tkrtYzKLOsM6dvCH8VRwYCYrxKYLxp_iikgopRc6Uxw2Hw)

## Additional Context

Satori Version: 0.10.4
Next.js Version: 13.4.20-canary.21 (Tested on stable version also)

**Comment by shuding** [comment] 2023-10-06 16:49
Duplicate of #215.

**Closed by shuding** 2023-10-06 16:49 UTC
