### ISSUE TITLE
Devanagari/Indic/Hindi font not rendering correctly

### ISSUE THREAD

**Issue by dvrfluxchat** [vercel/satori#516] opened 2023-07-04 16:54 UTC
# Bug Report

## Description / Observed Behavior

I am facing an issue where Satori is not able to render Indic/Devanagiri font correctly. When I input text in Indic/Devanagiri script, the rendered output appears distorted and unreadable. 

## Expected Behavior

I expected Satori to accurately render Indic/Devanagiri fonts, displaying the characters in a legible and coherent manner. The text should appear correctly, without any distortion or rendering errors.

## Reproduction

To reproduce the issue, please follow these steps:

1. Go to https://og-playground.vercel.app.
2. Select the input field for entering text.
3. Type or paste Indic/Devanagiri script into the input field.
4. Observe the rendered output and notice the incorrect rendering or distortion of the Indic/Devanagiri font.
5.  "ॐ मन्त्रार्थाः सफला: सन्तु पूर्णाः सन्तु मनोरथाः" - Look at the rendered text for this.

Sample Image from playground
![Screenshot 2023-07-04 at 10 18 24 PM](https://github.com/vercel/satori/assets/62265470/ee6c0a63-923b-4917-81c2-828c2bffd8fa)

**Comment by shuding** [comment] 2023-10-06 17:01
This is a duplicate of #215 - we do have something on our roadmap but this is tricky and might take a while.

**Closed by shuding** 2023-10-06 17:01 UTC
