### ISSUE TITLE
Color in hsl is not applied when using deg units (local hosted)

### ISSUE THREAD

**Issue by Arctomachine** [vercel/satori#374] opened 2023-01-16 12:39 UTC
# Bug report

## Description / Observed Behavior

When defining color in `hsl`, if it has `deg` units, it is not applied, black is used instead. Example: `hsl(200deg, 50%, 50%)` - expected blue, results in black. Bug appears when local hosted, but not in playground.

Result in local project:
![image](https://user-images.githubusercontent.com/29041820/212678154-7ebb31b7-e2dc-476a-871f-ca2d036fc06f.png)

Result in playground:
![image](https://user-images.githubusercontent.com/29041820/212678042-ecb4c1a5-c4a6-4d77-9f42-9d9715668e13.png)

## Expected Behavior

Results should be identical, both words must be blue in local project

## Reproduction
As mentioned above, it works in playground.
https://og-playground.vercel.app/?share=hZNva9swEMa_yiEoScAsTtigiCQwunbbm73Z3gz8RrHOtjJZMpK81Av-7jvZ_Ze2bs8gpOP3HPLdoxPLrUTG2XIJN0Lrvcj_QGFN8CCMhOvaHhQIhyA7I2qVE9KBtkKizAxpCmdr-GptqRFuHmRXX354UAZCpTxIrO2HzAz4b9tCLgwI7S04DK2jPRStyYOyBnJbN9agCaMYodGiK51tjaQK8wVsd3DKDBBofKBVW7eCLcwqr-frNJVYJvApvRiWxewZuX5CnmMRvLvNPO4fYyPV3_NMDB86jdvTcJWXEdv3U_1DDqv1ZfI6E_s8_hiH2bFSAWcT5FHJUBG0StOLKaZCVVbhHUgqH9tJVKHxdooKeBs-a1Ua4nKaBLopUkTqe8Dav4seWh9U0V1RY4h7E-_789yOphPGb0xsfEMGup_AMFh-54S-331DrW2yWUaIpOe1p6Vrkh6t0_JV5WZJLniSW2SmB8gMS5htonE94yc2DIrxSzIXGwfC-Md4kLhvS8YLMj0mjF7DQf3qmvjownE4UZ3omet6j5Lx4Frs-_8

But same code is not working in local project.
Here is entire code from /api/og endpoint
```js
// pages/api/og.tsx
import {ImageResponse} from '@vercel/og';

export const config = {
    runtime: 'edge',
};

export default function Og() {
    const color1 = 'hsl(200deg, 50%, 50%)'
    const color2 = 'hsl(200, 50%, 50%)'

    return new ImageResponse(
        (
            <div
                style={{
                    fontSize: 128,
                    background: 'white',
                    width: '100%',
                    height: '100%',
                    display: 'flex',
                    textAlign: 'center',
                    alignItems: 'center',
                    justifyContent: 'center',
                }}
            >
                <span style={{color: color1}}>Hello,</span>
                <span style={{color: color2}}>world</span>
            </div>
        ),
        {
            width: 800,
            height: 400,
        },
    );
}
```
## Additional Context

Project settings:

- environment: node.js 16.15.1 lts
- react: 18.2.0
- next: 13.1.2
- @vercel/og: 0.0.27

**Comment by sahithyandev** [comment] 2023-01-18 06:03
I tried to find the cause of this bug. And I couldn't find it.

**Comment by Arctomachine** [comment] 2023-01-18 06:21
Can it be caused by differences between normal edge runtime and its node emulation?

**Comment by Arctomachine** [comment] 2023-02-02 16:43
Node 18 lts (`v18.13.0`), still getting this bug.

**Comment by shuding** [comment] 2023-02-07 08:43
Can you try latest `@vercel/og`?

**Comment by Arctomachine** [comment] 2023-02-09 10:23
Issue remains in latest version `0.1.0` and beta version `0.2.0-beta.0`

**Comment by Arctomachine** [comment] 2023-02-09 10:33
I checked my sandbox link again and found out this.
1. When it is set to svg output, everything works
![image](https://user-images.githubusercontent.com/29041820/217787476-c66da929-5fd6-4a6a-b1b2-74f1dc903b33.png)
2. When set to png output, it behaves the same way as in my local project, where it is also png
![image](https://user-images.githubusercontent.com/29041820/217787726-184f3b35-8c0f-46d2-8366-1ec3acd4049b.png)
3. And in pdf output all colors are black
![image](https://user-images.githubusercontent.com/29041820/217787974-a42488da-608c-4baf-ba3d-777473d12997.png)

Does it help to narrow down this issue?

**Comment by shuding** [comment] 2023-02-10 20:24
Thanks! Since the SVG is correct, this should be something in Resvg (handles SVG → PNG). I'll upgrade that lib and see if it's fixed in the upstream.

**Comment by shuding** [comment] 2023-02-10 20:28
Just verified, this is indeed caused by https://github.com/RazrFalcon/resvg, you can open an issue there — however I'd like to also work around it inside Satori by removing the `deg` when generating the SVG.

**Comment by yisibl** [comment] 2023-02-17 11:22
resvg has no plans to implement this https://github.com/RazrFalcon/resvg/issues/579, I think it would be better to implement it separately in this library.

**Closed** 2023-04-18 12:11 UTC
Labels: bug
